#!/bin/bash

brightness_values=$(xrandr --verbose | grep -i brightness | awk '{print $2}')

for value in $brightness_values; do
    if (( $(echo "$value < 1" | bc -l) )); then
        xrandr --output DP-0 --brightness 1
        xrandr --output HDMI-0 --brightness 1
    else
        xrandr --output DP-0 --brightness 0.5
        xrandr --output HDMI-0 --brightness 0.5
    fi
done
